CREATE TABLE IF NOT EXISTS PRODUCT
(
    ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    MAKE VARCHAR(100) NOT NULL,
    PRICE DOUBLE NOT NULL,
    QUANTITY INTEGER NOT NULL,
    DESCRIPTION VARCHAR(800),
    IMAGE VARCHAR(500),
    CART_ID INTEGER NOT NULL,
    PROVIDER_ID INTEGER NOT NULL ,

    /*FOREIGN KEY (CART_ID) REFERENCES CART (ID),*/
    FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDER (ID)

);
