CREATE TABLE IF NOT EXISTS PROVIDER_CONTACT
(
    ID               INTEGER       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TELEPHONE_NUMBER INTEGER       NOT NULL,
    EMAIL_ADDRESS    VARCHAR(100) NOT NULL,
    FAX              INTEGER       NOT NULL,
    PROVIDER_ID      INTEGER       NOT NULL,
    FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDER (ID)

);
