CREATE TABLE IF NOT EXISTS PROVIDER_ADDRESS
(
    ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    STREET VARCHAR(200) NOT NULL,
    NUMBER INTEGER NOT NULL,
    POST_CODE VARCHAR(50) NOT NULL,
    TOWN VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL,

    PROVIDER_CONTACT_ID INTEGER NOT NULL,

    FOREIGN KEY (PROVIDER_CONTACT_ID) REFERENCES PROVIDER_CONTACT (ID)

);
